### ISSUE TITLE
Grab a threat intel platform/suite

### ISSUE THREAD

**Issue by samuel-barrows** [samuel-barrows/capstone#23]
Research different threat intel platforms/suites and choose one and acquire access.

**Comment by DamSimm** [comment]
Some sources to consider:
- [ ] Alienvault
- [ ] MalwareBazaar
- [ ] MITRE APT
- [ ] Mandiant?

**Comment by DamSimm** [comment]
https://attack.mitre.org/groups/

This provides very easy to digest APT groups with associated tactics pre mapped to the MITRE ATT&CK framework.
